#25570 : Redis / Session-less testing and improvements
dotCMS/tomcat-redis-session-manager pull request #2
Opened 2023-08-17 21:56 UTC by jcastro-dotcms

2023-08-18 15:12 UTC, wezell requested changes
Small change which I think makes sense

2023-08-18 15:12 UTC, wezell commented on src/main/java/com/dotcms/tomcat/redissessions/RedisSession.java
>              super.removeAttribute(key);
I would not remove it from the in memory session - meaning, we still might want it in memory.  I would just not add it to the redis session.

2023-08-21 17:40 UTC, jcastro-dotcms commented on src/main/java/com/dotcms/tomcat/redissessions/RedisSession.java
>              super.removeAttribute(key);
Done!

2023-08-21 18:01 UTC, jdotcms approved these changes

2023-08-23 16:15 UTC, wezell approved these changes

2023-08-23 16:16 UTC, merged